languageCode = "es-es"
title = "Desatascos Valencia – tuberias y fosas sépticas | Lyd Valencia"
baseurl = "https://www.limpiezasydesatascosvalencia.es"
theme = "landing-page-hugo"
disableHugoGeneratorInject = true

[params]
description = "Desatasco de tuberías y limpieza de fosas. Valencia y alrededores. 24 horas."
alert = "Servicios disponibles a partir de diciembre de 2017!"
custom_css = ["css/local.css"]
header = "LYD Valencia"
title = "Limpiezas y Desatascos Valencia S.L."
googleAnalytics = "UA-110224542-1"

[[params.social]]
    title = "644 714 500"
    icon = "phone"
    url = "tel: +34644714500"

[[params.social]]
    title = "Whatsapp"
    icon = "whatsapp"
    url = "https://api.whatsapp.com/send?phone=34644714500"
[[params.social]]
    title = "contacto@lydvalencia.es"
    icon = "envelope-o"
    url = "mailto:contacto@lydvalencia.es"
